uploads = []

[[generated]]
id = "sZpc0aS1c9EZqdFEZ-BuB"
uri = "file://artifacts/atomic-flix/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "mP5hwFxYIXKwAZiOB85Bv"
uri = "file://artifacts/atomic-flix/assets/images/splash.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "Mga58eah76zgqY7Cie1x7"
uri = "file://README.md"
type = "text"
title = "README GitHub — ATOMIC FLIX"

[[outputs]]
id = "WnUKsWsUpEurIeuId6LZI"
uri = "file://artifacts/atomic-flix/assets/images/icon_preview.png"
type = "image"
title = "Icon Final — A ⛛ F serrés"

[[outputs]]
id = "X6JHkP8JKBpgBfMWcylbu"
uri = "file://artifacts/atomic-flix/store-listing.md"
type = "text"
title = "ATOMIC FLIX — Fiche de publication store"
